### ISSUE TITLE
Touchbar wont start unil restart

### ISSUE THREAD

**Issue by Mindst0rms** [NoaHimesaka1873/manjaroiso-t2#1]
It seems that my only problem is the touchbar doesn't start without a restart of the computer, and sometimes turns off while using the OS. I think these logfiles might help.
[Xorg.1.log](https://github.com/NoaHimesaka1873/manjaroiso-t2/files/9490947/Xorg.1.log)
[pacman.log](https://github.com/NoaHimesaka1873/manjaroiso-t2/files/9490949/pacman.log)

**Comment by NoaHimesaka1873** [comment]
> It seems that my only problem is the touchbar doesn't start without a restart of the computer, and sometimes turns off while using the OS. I think these logfiles might help.
> 
> [Xorg.1.log](https://github.com/NoaHimesaka1873/manjaroiso-t2/files/9490947/Xorg.1.log)
> 
> [pacman.log](https://github.com/NoaHimesaka1873/manjaroiso-t2/files/9490949/pacman.log)
> 
> 

Unrelated log files, apple-bce and apple-ib modules are still WIP so that can happen. Please report those issues (with dmesg log) in #general at t2linux Discord.

Closing as CANTFIX.
