### ISSUE TITLE
hosting the files

### ISSUE THREAD

**Issue by monomycelium** [NoaHimesaka1873/manjaroiso-t2#2]
### the problem

i just realised that i need both `.zip` and `.z01`, which i found out from [mikeeq/fedora](https://github.com/mikeeq/mbp-fedora#how-to-install). i was stuck for hours trying to unzip the disk images, thinking that they were two different complete zip archives.

### my suggestion

i hope you would add that part (that i have to join the archives) to the [readme](https://github.com/NoaHimesaka1873/manjaroiso-t2#readme), or the [installation wiki](https://wiki.t2linux.org/distributions/manjaro/installation/) because i had no idea zip archives could be split. and i do hope you would use torrents (this also acts as my offer to host all the files) so i get faster speeds as well as less of a hassle downloading.

---

<details>
<summary>my issue that is not an issue</summary>

after downloading `manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip`, i opened it with my archive manager. however, it showed an error about multi-disk images.

![Screenshot_20220924_135242](https://user-images.githubusercontent.com/95113443/192082527-a70155af-85c7-448f-9823-968a111e404e.png)

so i resorted to `7z` from `p7zip`. but i got the same error.

```
╭─mycelium@asahi:~/Downloads 
╰─🐧 $ 7z l manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_SG.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 1177224527 bytes (1123 MiB)

Listing archive: manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip

--
Path = manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip
Type = zip
ERROR = Missing volume : manjaro-kde-22.8-t2-220818-linux519-t2.iso.z01
Physical Size = 1177224527
Total Physical Size = 1177224527
Multivolume = +
Volume Index = 1
Volumes = 2

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-08-18 15:38:30 .....   3250700288   3221947489  manjaro-kde-22.8-t2-220818-linux519-t2.iso
------------------- ----- ------------ ------------  ------------------------
2022-08-18 15:38:30         3250700288   3221947489  1 files

Errors: 1
```

so i forced `7z` to extract it anyway.

```
╭─mycelium@asahi:~/Downloads 
╰─🐧 $ 7z x manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip                                                2 ↩

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_SG.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 1177224527 bytes (1123 MiB)

Extracting archive: manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip

ERRORS:
Missing volume : manjaro-kde-22.8-t2-220818-linux519-t2.iso.z01

--
Path = manjaro-kde-22.8-t2-220818-linux519-t2.iso.zip
Type = zip
ERROR = Missing volume : manjaro-kde-22.8-t2-220818-linux519-t2.iso.z01
Physical Size = 1177224527
Total Physical Size = 1177224527
Multivolume = +
Volume Index = 1
Volumes = 2

ERROR: Unavailable data : manjaro-kde-22.8-t2-220818-linux519-t2.iso
                                                 
Sub items Errors: 1

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 1
```

i did get an extracted disk image, or so i thought. the checksums do not match:

```
╭─mycelium@asahi:~/Downloads 
╰─🐧 $ sha256sum manjaro-kde-22.8-t2-220818-linux519-t2.iso -c manjaro-kde-22.8-t2-220818-linux519-t2.iso.sha256
sha256sum: manjaro-kde-22.8-t2-220818-linux519-t2.iso: no properly formatted checksum lines found
manjaro-kde-22.8-t2-220818-linux519-t2.iso: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
╭─mycelium@asahi:~/Downloads 
╰─🐧 $ sha256sum manjaro-kde-22.8-t2-220818-linux519-t2.iso                                               1 ↩
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  manjaro-kde-22.8-t2-220818-linux519-t2.iso
╭─mycelium@asahi:~/Downloads 
╰─🐧 $ cat manjaro-kde-22.8-t2-220818-linux519-t2.iso.sha256
5b7956da2ab36e54d0bca92f3bc86ca6cbec27869cf55158180a131399cb4956  manjaro-kde-22.8-t2-220818-linux519-t2.iso
```

and after flashing it, my usb stick does not even bother showing up on the boot screen from apple. even though arch linux booted just fine from the same stick.

so naturally, i am annoyed. not at you guys, but at apple. why does apple always have to lock everything? if *they* supported the upstream linux kernel directly on their macs, it would be so much easier to install linux using disk images (built properly) that can be downloaded safely (and more quickly), like from official torrents and whatnot!

anyway, i'm not here to rant about apple to you. i hope you would find a way to build the image safely, archive it properly (maybe using `.tar.xz` instead of the wonky `.zip`?), and distribute it on faster platforms (like torrents). i know that may be a hassle, considering that t2 macs are being phased out and people do not care about gnu + linux, but i am looking forward to having better support on my t2 mac.

</summary>

**Comment by NoaHimesaka1873** [comment]
Fixed the wiki.
