### ISSUE TITLE
unable to boot after repartition

### ISSUE THREAD

**Issue by monomycelium** [NoaHimesaka1873/manjaroiso-t2#3]
i had a fully-working manjaro-t2 installation on my 2020 13" macbook pro. i wanted to resize some partitions so that i my manjaro rootfs could be larger.

in macos, i shrunk my mac partition and created a new temporary partition that i intended to remove. this worked successfully, leaving my mac files and linux partitions intact.

then, i attempted to boot into manjaro. however, `grub rescue` showed up to mock me. i tried again, but the same thing happened =(.

so i resorted to fixing stuff from a live installation of manjaro an sd card. this booted just fine (with a usb adapter). i removed the temporary partition that i was going to remove. i did not resize the manjaro rootfs. i `chroot`ed into my internal manjaro installation. i performed `update-grub` and `grub-mkconfig`. it showed two errors about `/dev/sda?` not supported or something.

i tried booting into my internal manjaro again, but the same thing happened: the `grub rescue` screen of doom.

what should i do? thank you in advance (because the strong linux community always finds its way!).

**Comment by NoaHimesaka1873** [comment]
Reinstall GRUB. You did something wrong to your EFI partition.
Come to t2linux Discord for faster help.

**Comment by NoaHimesaka1873** [comment]
Also, for support please go to t2linux Discord. This is strictly for issues related to ISO only. Closing.
